FROM --platform=$BUILDPLATFORM squidfunk/mkdocs-material:9.6 as build

WORKDIR /build
COPY site/ /build/

# Install social plugin dependencies
RUN pip install pillow cairosvg

# Build the site
RUN mkdocs build

# Use a lightweight web server to serve the static site
FROM nginx:alpine
COPY --from=build /build/site /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
